title: Teste blog EPTA
description: descrição do teste

url: https://olavocinacio.github.io
baseurl: "/long-haul"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: teste
  twitter: teste
  facebook: teste
  email: brimaidesigns@gmail.com
  linkedin: teste

google_analytics: "AAAAA"

disqus:
    shortname: teste
